"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {api} from "@/services/api";
import type {VinResolution} from "@/types";

export default function VehicleResolutionPage(){
 const [vin,setVin]=useState(""),[country,setCountry]=useState("FR"),[year,setYear]=useState(""),[result,setResult]=useState<VinResolution|null>(null),[selected,setSelected]=useState(""),[engine,setEngine]=useState(""),[transmission,setTransmission]=useState(""),[make,setMake]=useState(""),[model,setModel]=useState(""),[market,setMarket]=useState("FR"),[fuel,setFuel]=useState(""),[note,setNote]=useState(""),[vehicleId,setVehicleId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function resolve(e:FormEvent){e.preventDefault();setBusy(true);setError("");setVehicleId("");try{const validation=await api.validateVin(vin);if(!validation.is_valid_format)throw new Error(validation.errors.join(" "));const data=await api.resolveVin({vin:validation.normalized_vin,country_code:country||null,model_year_hint:year?Number(year):null});setResult(data);setSelected(data.candidates[0]?.id??"");setEngine(data.candidates[0]?.engine_code??"");setTransmission(data.candidates[0]?.transmission_type??"")}catch(e){setError(e instanceof Error?e.message:"Résolution impossible")}finally{setBusy(false)}}
 function choose(id:string){setSelected(id);const item=result?.candidates.find(x=>x.id===id);setEngine(item?.engine_code??"");setTransmission(item?.transmission_type??"")}
 async function confirm(unknown=false){if(!result)return;setBusy(true);setError("");try{const item=result.candidates.find(x=>x.id===selected);const corrections:Record<string,string|number>={};if(engine&&engine!==item?.engine_code)corrections.engine_code=engine;if(transmission&&transmission!==item?.transmission_type)corrections.transmission_type=transmission;if(!item){if(make)corrections.make=make;if(model)corrections.model=model;if(year)corrections.model_year=Number(year);if(market)corrections.market=market;if(fuel)corrections.fuel_type=fuel}const data=await api.confirmResolution(result.id,{candidate_id:selected||null,corrections,technician_note:note||null,configuration_unknown:unknown});setVehicleId(data.vehicle.id);setResult(data.resolution)}catch(e){setError(e instanceof Error?e.message:"Confirmation impossible")}finally{setBusy(false)}}
 return <div className="mx-auto max-w-5xl space-y-8"><div><p className="eyebrow">Identification véhicule · étape 1 sur 2</p><h1 className="mt-2 text-3xl font-bold md:text-4xl">Résoudre une configuration par VIN</h1><p className="mt-3 max-w-3xl text-muted">Le VIN est chiffré côté serveur et reste masqué dans l’interface. Vous gardez toujours la décision finale sur la configuration.</p></div>
 <form onSubmit={resolve} className="card grid gap-5 md:grid-cols-[2fr_1fr_1fr_auto]"><div><label htmlFor="vin" className="label">VIN complet ou partiel *</label><input id="vin" required minLength={3} maxLength={24} autoCapitalize="characters" spellCheck={false} className="field font-mono uppercase" value={vin} onChange={e=>setVin(e.target.value)} aria-describedby="vin-help"/><p id="vin-help" className="mt-2 text-sm text-muted">Démo : ZZZTESTA0DEMA0001. Les espaces et tirets sont acceptés.</p></div><div><label htmlFor="country" className="label">Pays</label><input id="country" maxLength={2} className="field uppercase" value={country} onChange={e=>setCountry(e.target.value)}/></div><div><label htmlFor="year" className="label">Année estimée</label><input id="year" type="number" min="1886" max="2100" inputMode="numeric" className="field" value={year} onChange={e=>setYear(e.target.value)}/></div><button disabled={busy} className="btn-primary self-end">{busy?"Recherche…":"Rechercher"}</button></form>
 {error&&<div role="alert" className="rounded-xl border border-danger bg-red-950/30 p-4 text-red-100"><strong>Action impossible.</strong> {error}</div>}
 {result&&<section aria-live="polite" className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Résultat {result.cache_hit?"en cache":"du fournisseur"}</p><h2 className="mt-1 text-2xl font-bold">VIN {result.masked_vin}</h2></div><span className="badge">État : {result.status.replaceAll("_"," ")}</span></div>
 {result.error_message&&<div className="card border-warning/60"><h3 className="font-semibold text-amber-200">Mode manuel disponible</h3><p className="mt-2 text-muted">{result.error_message}</p></div>}
 <div className="grid gap-4 md:grid-cols-2">{result.candidates.map((item,index)=><label key={item.id} className={`card cursor-pointer transition-colors ${selected===item.id?"border-primary ring-2 ring-primary/40":"hover:border-slate-500"}`}><span className="flex items-start gap-3"><input className="mt-1 h-5 w-5" type="radio" name="candidate" checked={selected===item.id} onChange={()=>choose(item.id)}/><span className="min-w-0 flex-1"><span className="eyebrow">Configuration {index+1} · confiance {Math.round(item.confidence_score*100)} %</span><strong className="mt-2 block text-xl">{item.make??"Marque inconnue"} {item.model??"Modèle inconnu"}</strong><span className="mt-3 grid gap-2 text-sm text-muted sm:grid-cols-2"><span>Année : {item.model_year??"à confirmer"}</span><span>Marché : {item.market??"à confirmer"}</span><span>Carburant : {item.fuel_type??"à confirmer"}</span><span>Moteur : {item.engine_code??"à confirmer"}</span><span>Puissance : {item.engine_power_kw?`${item.engine_power_kw} kW`:"à confirmer"}</span><span>Boîte : {item.transmission_type??"à confirmer"}</span><span>Variante : {item.type_variant_version??"à confirmer"}</span><span>Source : {item.provider_name}</span></span>{item.missing_critical_fields.length>0&&<span className="mt-4 block rounded-lg border border-warning/50 bg-amber-950/20 p-3 text-sm text-amber-100">À compléter : {item.missing_critical_fields.join(", ")}</span>}</span></span></label>)}</div>
 {result.candidates.length>0&&<div className="card"><h3 className="text-lg font-semibold">Vérification technicien</h3><p className="mt-1 text-sm text-muted">Corrigez uniquement ce que vous avez vérifié sur le véhicule.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><label className="label" htmlFor="engine">Code moteur</label><input id="engine" className="field" value={engine} onChange={e=>setEngine(e.target.value)}/></div><div><label className="label" htmlFor="transmission">Transmission</label><input id="transmission" className="field" value={transmission} onChange={e=>setTransmission(e.target.value)}/></div></div><div className="mt-5"><label className="label" htmlFor="note">Note technicien</label><textarea id="note" className="field min-h-24" value={note} onChange={e=>setNote(e.target.value)}/></div><div className="mt-6 flex flex-wrap justify-end gap-3 border-t border-line pt-5"><button type="button" className="btn-secondary" onClick={()=>setResult(null)}>Recommencer</button><button type="button" className="btn-primary" disabled={busy||!selected} onClick={()=>confirm()}>{busy?"Confirmation…":"Confirmer la configuration"}</button></div></div>}
 {result.candidates.length===0&&<div className="card"><h3 className="text-lg font-semibold">Identification manuelle</h3><p className="mt-1 text-sm text-muted">Renseignez uniquement les informations vérifiées, ou conservez une configuration inconnue.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><label className="label" htmlFor="manual-make">Marque</label><input id="manual-make" className="field" value={make} onChange={e=>setMake(e.target.value)}/></div><div><label className="label" htmlFor="manual-model">Modèle</label><input id="manual-model" className="field" value={model} onChange={e=>setModel(e.target.value)}/></div><div><label className="label" htmlFor="manual-market">Marché</label><input id="manual-market" className="field" value={market} onChange={e=>setMarket(e.target.value)}/></div><div><label className="label" htmlFor="manual-fuel">Carburant</label><input id="manual-fuel" className="field" value={fuel} onChange={e=>setFuel(e.target.value)}/></div><div><label className="label" htmlFor="manual-engine">Code moteur</label><input id="manual-engine" className="field" value={engine} onChange={e=>setEngine(e.target.value)}/></div><div><label className="label" htmlFor="manual-transmission">Boîte</label><input id="manual-transmission" className="field" value={transmission} onChange={e=>setTransmission(e.target.value)}/></div></div><div className="mt-5"><label className="label" htmlFor="manual-note">Note technicien</label><textarea id="manual-note" className="field min-h-24" value={note} onChange={e=>setNote(e.target.value)}/></div><div className="mt-6 flex flex-wrap justify-end gap-3 border-t border-line pt-5"><Link href="/" className="btn-secondary">Reporter</Link><button type="button" className="btn-secondary" disabled={busy} onClick={()=>confirm(true)}>Configuration inconnue</button><button type="button" className="btn-primary" disabled={busy||!make||!model} onClick={()=>confirm()}>{busy?"Enregistrement…":"Enregistrer manuellement"}</button></div></div>}
 {vehicleId&&<div role="status" className="card border-success/60 bg-emerald-950/20"><h3 className="text-xl font-bold text-emerald-100">Configuration confirmée</h3><p className="mt-2 text-muted">Le véhicule est prêt pour la sélection des codes défauts et l’analyse.</p><Link href="/diagnostics/new" className="btn-primary mt-5">Démarrer un diagnostic</Link></div>}</section>}</div>
}
