"use client";

import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {API,api} from "@/services/api";
import type {DiagnosticDetail} from "@/types";

type ImageDraft={file:File;preview:string;category:string;description:string};
const urgencyStyle={low:"border-emerald-300 bg-emerald-50 text-emerald-800",medium:"border-amber-300 bg-amber-50 text-amber-800",high:"border-orange-600 bg-orange-950/30 text-orange-100",critical:"border-red-300 bg-red-100 text-red-800"};
const confidence=(value:number)=>value>=.75?"Confiance élevée":value>=.4?"Confiance moyenne":"Confiance faible";
const sourceLabel:Record<string,string>={provided_by_database:"base locale fiable",ai_general_knowledge:"raisonnement IA (base locale non fiable ou absente)",not_found:"définition non trouvée"};
const origin=API.replace(/\/api\/?$/,"");

export default function AIDiagnosticConsole(){
 const {id}=useParams<{id:string}>();const [detail,setDetail]=useState<DiagnosticDetail|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [outcome,setOutcome]=useState("");const [comment,setComment]=useState("");
 const [newCode,setNewCode]=useState("");const [newEcu,setNewEcu]=useState("");const [newStatus,setNewStatus]=useState<"active"|"intermittent"|"stored"|"unknown">("unknown");
 const [measureName,setMeasureName]=useState("");const [measureValue,setMeasureValue]=useState("");const [measureUnit,setMeasureUnit]=useState("");
 const [pendingImages,setPendingImages]=useState<ImageDraft[]>([]);
 const load=useCallback(async()=>{try{setDetail(await api.diagnostic(id));setError("")}catch(e){setError(e instanceof Error?e.message:"Chargement impossible")}},[id]);useEffect(()=>{load()},[load]);
 const current=detail?.steps.find(x=>x.status==="current");
 async function saveResult(){if(!current||!outcome.trim())return setError("Décrivez le résultat constaté.");setBusy(true);setError("");try{await api.submitStepResult(id,current.id,{outcome,measurement:null,unit:null,comment});await api.reanalyzeDiagnostic(id);setOutcome("");setComment("");await load()}catch(e){setError(e instanceof Error?e.message:"Réévaluation impossible")}finally{setBusy(false)}}
 async function reanalyze(){setBusy(true);setError("");try{await api.reanalyzeDiagnostic(id);await load()}catch(e){setError(e instanceof Error?e.message:"Réévaluation impossible")}finally{setBusy(false)}}
 async function addFaultCode(){if(!newCode.trim())return setError("Saisissez un code défaut.");setBusy(true);setError("");try{await api.addFaultCodes(id,{fault_codes:[{code:newCode.trim().toUpperCase(),ecu:newEcu.trim()||null,status:newStatus,freeze_frame:{}}]});setNewCode("");setNewEcu("");setNewStatus("unknown");await api.reanalyzeDiagnostic(id);await load()}catch(e){setError(e instanceof Error?e.message:"Ajout du code impossible")}finally{setBusy(false)}}
 async function addMeasurementQuick(){if(!measureName.trim())return setError("Nommez la mesure.");setBusy(true);setError("");try{const numeric=Number(measureValue);await api.addMeasurement(id,{name:measureName,value:Number.isFinite(numeric)&&measureValue.trim()!==""?numeric:measureValue,unit:measureUnit.trim()||null,conditions:"",source:"manual"});setMeasureName("");setMeasureValue("");setMeasureUnit("");await api.reanalyzeDiagnostic(id);await load()}catch(e){setError(e instanceof Error?e.message:"Ajout de la mesure impossible")}finally{setBusy(false)}}
 function addPendingImages(list:FileList|File[]){const accepted=Array.from(list).filter(file=>["image/jpeg","image/png","image/webp"].includes(file.type));setPendingImages(current=>[...current,...accepted.slice(0,8-current.length).map(file=>({file,preview:URL.createObjectURL(file),category:"engine_bay",description:""}))]);if(accepted.length!==Array.from(list).length)setError("Certains fichiers ont été ignorés : utilisez JPEG, PNG ou WebP.")}
 function removePendingImage(index:number){setPendingImages(current=>{URL.revokeObjectURL(current[index].preview);return current.filter((_,i)=>i!==index)})}
 async function uploadPendingImages(){if(!pendingImages.length)return;setBusy(true);setError("");try{for(const item of pendingImages){const data=new FormData();data.append("files",item.file);data.append("category",item.category);data.append("description",item.description);await api.uploadImages(id,data)}pendingImages.forEach(item=>URL.revokeObjectURL(item.preview));setPendingImages([]);await api.reanalyzeDiagnostic(id);await load()}catch(e){setError(e instanceof Error?e.message:"Ajout des photos impossible")}finally{setBusy(false)}}
 if(!detail)return <div className="card" role="status">{error||"Chargement de l’analyse…"}</div>;
 const analysis=detail.analysis;if(!analysis)return <div className="card"><h1 className="text-2xl font-bold">Analyse indisponible</h1><p className="mt-2 text-muted">Le dossier existe, mais aucune sortie IA validée n’a été enregistrée.</p><button className="btn-primary mt-5" disabled={busy} onClick={reanalyze}>Relancer</button></div>;
 return <div className="space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Dossier IA · {id.slice(0,8)}</p><h1 className="mt-2 text-3xl font-bold">{detail.vehicle.make} {detail.vehicle.model}</h1><p className="mt-1 text-muted">{detail.vehicle.engine_name} · {detail.case.mileage?.toLocaleString("fr-FR")??"kilométrage inconnu"} km</p></div><div className="flex gap-3"><Link href="/diagnostics/new" className="btn-secondary">Nouveau dossier</Link><button className="btn-primary" disabled={busy} onClick={reanalyze}>{busy?"Réévaluation…":"Réévaluer"}</button></div></div>
  {error&&<div role="alert" className="rounded-xl border border-danger bg-red-50 p-4 text-red-800">{error}</div>}

  <section className="card" aria-labelledby="add-evidence-title"><p className="eyebrow">Enrichir le dossier</p><h2 id="add-evidence-title" className="mt-2 text-2xl font-bold">Ajouter des éléments pendant le diagnostic</h2><p className="mt-1 text-sm text-muted">Ajoutez un code, une mesure ou des photos à tout moment ; l’analyse est automatiquement relancée avec les nouveaux éléments.</p>
   <div className="mt-5 grid gap-6 lg:grid-cols-3">
    <fieldset><legend className="label">Code défaut</legend><input className="field font-mono uppercase" placeholder="P0301" value={newCode} onChange={e=>setNewCode(e.target.value)} maxLength={5}/><input className="field mt-2" placeholder="Calculateur (optionnel)" value={newEcu} onChange={e=>setNewEcu(e.target.value)}/><select className="field mt-2" value={newStatus} onChange={e=>setNewStatus(e.target.value as typeof newStatus)}><option value="unknown">Statut inconnu</option><option value="active">Actif</option><option value="intermittent">Intermittent</option><option value="stored">Mémorisé</option></select><button type="button" className="btn-secondary mt-2 w-full" disabled={busy} onClick={addFaultCode}>Ajouter le code et réévaluer</button></fieldset>
    <fieldset><legend className="label">Mesure</legend><input className="field" placeholder="Pression rail" value={measureName} onChange={e=>setMeasureName(e.target.value)}/><input className="field mt-2" placeholder="250" value={measureValue} onChange={e=>setMeasureValue(e.target.value)}/><input className="field mt-2" placeholder="bar" value={measureUnit} onChange={e=>setMeasureUnit(e.target.value)}/><button type="button" className="btn-secondary mt-2 w-full" disabled={busy} onClick={addMeasurementQuick}>Ajouter la mesure et réévaluer</button></fieldset>
    <fieldset><legend className="label">Photos</legend><label htmlFor="add-images" className="flex min-h-24 cursor-pointer items-center justify-center rounded-[2px] border-2 border-dashed border-line bg-canvas p-3 text-center text-sm transition-colors hover:border-amber-300" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addPendingImages(e.dataTransfer.files)}}><span>Déposer des photos ou parcourir<br/><span className="text-xs text-muted">JPEG, PNG, WebP</span></span></label><input id="add-images" className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>e.target.files&&addPendingImages(e.target.files)}/>{pendingImages.length?<ul className="mt-2 space-y-1">{pendingImages.map((item,i)=><li key={item.preview} className="flex items-center justify-between gap-2 rounded-[2px] bg-panel px-2 py-1 text-xs"><span className="truncate">{item.file.name}</span><button type="button" className="text-red-700" onClick={()=>removePendingImage(i)}>Retirer</button></li>)}</ul>:null}<button type="button" className="btn-secondary mt-2 w-full" disabled={busy||!pendingImages.length} onClick={uploadPendingImages}>Ajouter {pendingImages.length||""} photo(s) et réévaluer</button></fieldset>
   </div>
  </section>

  <section className={`rounded-2xl border p-5 ${urgencyStyle[analysis.urgency.level]}`} aria-labelledby="urgency-title"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em]">Niveau d’urgence</p><h2 id="urgency-title" className="mt-1 text-2xl font-bold capitalize">{analysis.urgency.level}</h2></div><span className="badge">{analysis.urgency.drivingRecommendation.replaceAll("_"," ")}</span></div><p className="mt-3 max-w-4xl">{analysis.urgency.explanation}</p></section>
  <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(330px,.8fr)]"><main className="space-y-6">
   <section className="card"><p className="eyebrow">Synthèse</p><h2 className="mt-2 text-2xl font-bold">Ce que montre le dossier</h2><p className="mt-3 text-lg text-slate-600">{analysis.caseSummary}</p><div className="mt-4 rounded-[2px] border border-line bg-panel p-3"><p className="label mb-1">Méthode de raisonnement</p><p className="text-sm text-slate-600">{analysis.reasoningApproach}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{analysis.interpretedFaultCodes.map(code=><article key={code.code} className="rounded-xl border border-line bg-panel p-4"><div className="flex items-start justify-between gap-3"><strong className="font-mono text-lg text-amber-800">{code.code}</strong><span className="badge">{code.relevance}</span></div><p className="mt-2 text-sm">{code.meaning}</p><p className="mt-2 text-xs text-muted">{code.ecu||"Calculateur inconnu"} · {sourceLabel[code.sourceStatus]||code.sourceStatus}</p></article>)}</div>{analysis.correlations.map((item,i)=><div key={i} className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4"><strong>Corrélation à confirmer : {item.relatedCodes.join(" + ")}</strong><p className="mt-1 text-sm text-muted">{item.explanation}</p></div>)}</section>
   <section className="card"><p className="eyebrow">Raisonnement contrôlé</p><h2 className="mt-2 text-2xl font-bold">Hypothèses classées</h2><p className="mt-1 text-sm text-muted">La confiance exprime la cohérence avec les éléments présents, pas une probabilité scientifique.</p><div className="mt-5 space-y-4">{analysis.hypotheses.map((item,i)=><article key={item.id} className="rounded-xl border border-line bg-panel p-4"><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="font-semibold">{i+1}. {item.label}</h3><span className="badge">{confidence(item.confidence)} · {Math.round(item.confidence*100)}%</span></div>{item.component&&<p className="mt-1 text-sm text-amber-800">Composant : {item.component}</p>}<div className="mt-4 grid gap-4 md:grid-cols-2"><div><strong className="text-sm text-emerald-800">Éléments favorables</strong><ul className="mt-2 list-inside list-disc text-sm text-muted">{item.supportingEvidence.length?item.supportingEvidence.map(x=><li key={x}>{x}</li>):<li>Aucun élément direct</li>}</ul></div><div><strong className="text-sm text-amber-800">À confirmer / contradictions</strong><ul className="mt-2 list-inside list-disc text-sm text-muted">{[...item.contradictingEvidence,...item.requiredConfirmation].map(x=><li key={x}>{x}</li>)}</ul></div></div></article>)}</div></section>
   {analysis.imageEvidence.length?<section className="card"><p className="eyebrow">Vision</p><h2 className="mt-2 text-2xl font-bold">Éléments visuels</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{analysis.imageEvidence.map(item=>{const image=detail.images.find(x=>x.id===item.imageId);return <article key={item.imageId} className="overflow-hidden rounded-xl border border-line bg-panel">{image&&<img src={`${origin}${image.url}`} alt={image.description||`Image technique ${image.category}`} width={480} height={320} loading="lazy" className="aspect-video w-full object-cover"/>}<div className="p-4"><p>{item.observation}</p><p className="mt-2 text-xs text-muted">{item.limitations.join(" · ")}</p></div></article>})}</div></section>:null}
   <section className="card border-amber-300" aria-labelledby="next-check-title"><p className="eyebrow">Action suivante</p><h2 id="next-check-title" className="mt-2 text-2xl font-bold">{current?.title||analysis.nextChecks[0]?.title||"Aucun contrôle proposé"}</h2>{current&&<><p className="mt-3 text-lg">{current.objective}</p><ol className="mt-5 space-y-3">{current.instructions.map((instruction,i)=><li key={instruction} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-primary font-bold">{i+1}</span><span>{instruction}</span></li>)}</ol>{current.safety_notes.length?<div className="mt-5 rounded-xl border border-warning/50 bg-amber-50 p-4"><strong className="text-amber-800">Sécurité</strong><ul className="mt-2 list-inside list-disc text-sm">{current.safety_notes.map(x=><li key={x}>{x}</li>)}</ul></div>:null}<div className="mt-6 border-t border-line pt-5">{current.expected_results.length?<><p className="label">Résultats attendus</p><div className="mb-4 grid gap-2 sm:grid-cols-2">{current.expected_results.map(item=><button key={item.result_id} type="button" className="min-h-12 cursor-pointer rounded-xl border border-line bg-panel p-3 text-left text-sm hover:border-amber-300" onClick={()=>setOutcome(`${item.label} — ${item.meaning}`)}><strong className="block">{item.label}</strong><span className="text-muted">{item.meaning}</span></button>)}</div></>:null}<label className="label" htmlFor="outcome">Résultat constaté *</label><textarea id="outcome" className="field min-h-24" value={outcome} onChange={e=>setOutcome(e.target.value)} placeholder="Décrivez la mesure ou l’observation obtenue"/><label className="label mt-4" htmlFor="comment">Commentaire technicien</label><textarea id="comment" className="field min-h-20" value={comment} onChange={e=>setComment(e.target.value)}/><button className="btn-primary mt-4" disabled={busy||!outcome.trim()} onClick={saveResult}>{busy?"Enregistrement…":"Enregistrer et réévaluer"}</button></div></>}</section>
  </main><aside className="space-y-6 lg:sticky lg:top-6">
   <section className="card"><h2 className="text-xl font-semibold">Informations manquantes</h2><div className="mt-4 space-y-4">{analysis.missingInformation.map(item=><article key={item.field} className="border-t border-line pt-4 first:border-0 first:pt-0"><div className="flex justify-between gap-3"><strong>{item.field}</strong><span className="badge">{item.priority}</span></div><p className="mt-1 text-sm text-muted">{item.reason}</p><p className="mt-2 text-sm text-amber-800">À obtenir : {item.howToObtain}</p></article>)}</div></section>
   <section className="card"><h2 className="text-xl font-semibold">Conclusion actuelle</h2><span className="badge mt-3">{analysis.finalConclusion.status.replaceAll("_"," ")}</span><p className="mt-3 text-muted">{analysis.finalConclusion.summary}</p></section>
   <section className="card"><h2 className="text-xl font-semibold">Avertissements</h2><ul className="mt-3 list-inside list-disc space-y-2 text-sm text-muted">{analysis.warnings.map(x=><li key={x}>{x}</li>)}</ul></section>
  </aside></div>
 </div>
}
