"use client";

import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {API,api} from "@/services/api";
import type {DiagnosticDetail} from "@/types";

const urgencyStyle={low:"border-emerald-700 bg-emerald-950/30 text-emerald-100",medium:"border-amber-700 bg-amber-950/30 text-amber-100",high:"border-orange-600 bg-orange-950/30 text-orange-100",critical:"border-red-600 bg-red-950/40 text-red-100"};
const confidence=(value:number)=>value>=.75?"Confiance élevée":value>=.4?"Confiance moyenne":"Confiance faible";
const origin=API.replace(/\/api\/?$/,"");

export default function AIDiagnosticConsole(){
 const {id}=useParams<{id:string}>();const [detail,setDetail]=useState<DiagnosticDetail|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [outcome,setOutcome]=useState("");const [comment,setComment]=useState("");
 const load=useCallback(async()=>{try{setDetail(await api.diagnostic(id));setError("")}catch(e){setError(e instanceof Error?e.message:"Chargement impossible")}},[id]);useEffect(()=>{load()},[load]);
 const current=detail?.steps.find(x=>x.status==="current");
 async function saveResult(){if(!current||!outcome.trim())return setError("Décrivez le résultat constaté.");setBusy(true);setError("");try{await api.submitStepResult(id,current.id,{outcome,measurement:null,unit:null,comment});await api.reanalyzeDiagnostic(id);setOutcome("");setComment("");await load()}catch(e){setError(e instanceof Error?e.message:"Réévaluation impossible")}finally{setBusy(false)}}
 async function reanalyze(){setBusy(true);setError("");try{await api.reanalyzeDiagnostic(id);await load()}catch(e){setError(e instanceof Error?e.message:"Réévaluation impossible")}finally{setBusy(false)}}
 if(!detail)return <div className="card" role="status">{error||"Chargement de l’analyse…"}</div>;
 const analysis=detail.analysis;if(!analysis)return <div className="card"><h1 className="text-2xl font-bold">Analyse indisponible</h1><p className="mt-2 text-muted">Le dossier existe, mais aucune sortie IA validée n’a été enregistrée.</p><button className="btn-primary mt-5" disabled={busy} onClick={reanalyze}>Relancer</button></div>;
 return <div className="space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Dossier IA · {id.slice(0,8)}</p><h1 className="mt-2 text-3xl font-bold">{detail.vehicle.make} {detail.vehicle.model}</h1><p className="mt-1 text-muted">{detail.vehicle.engine_name} · {detail.case.mileage?.toLocaleString("fr-FR")??"kilométrage inconnu"} km</p></div><div className="flex gap-3"><Link href="/diagnostics/new" className="btn-secondary">Nouveau dossier</Link><button className="btn-primary" disabled={busy} onClick={reanalyze}>{busy?"Réévaluation…":"Réévaluer"}</button></div></div>
  {error&&<div role="alert" className="rounded-xl border border-danger bg-red-950/30 p-4 text-red-100">{error}</div>}
  <section className={`rounded-2xl border p-5 ${urgencyStyle[analysis.urgency.level]}`} aria-labelledby="urgency-title"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em]">Niveau d’urgence</p><h2 id="urgency-title" className="mt-1 text-2xl font-bold capitalize">{analysis.urgency.level}</h2></div><span className="badge">{analysis.urgency.drivingRecommendation.replaceAll("_"," ")}</span></div><p className="mt-3 max-w-4xl">{analysis.urgency.explanation}</p></section>
  <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(330px,.8fr)]"><main className="space-y-6">
   <section className="card"><p className="eyebrow">Synthèse</p><h2 className="mt-2 text-2xl font-bold">Ce que montre le dossier</h2><p className="mt-3 text-lg text-slate-200">{analysis.caseSummary}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{analysis.interpretedFaultCodes.map(code=><article key={code.code} className="rounded-xl border border-line bg-panel p-4"><div className="flex items-start justify-between gap-3"><strong className="font-mono text-lg text-amber-200">{code.code}</strong><span className="badge">{code.relevance}</span></div><p className="mt-2 text-sm">{code.meaning}</p><p className="mt-2 text-xs text-muted">{code.ecu||"Calculateur inconnu"} · {code.sourceStatus==="not_found"?"définition non trouvée":"base locale"}</p></article>)}</div>{analysis.correlations.map((item,i)=><div key={i} className="mt-4 rounded-xl border border-amber-900 bg-amber-950/20 p-4"><strong>Corrélation à confirmer : {item.relatedCodes.join(" + ")}</strong><p className="mt-1 text-sm text-muted">{item.explanation}</p></div>)}</section>
   <section className="card"><p className="eyebrow">Raisonnement contrôlé</p><h2 className="mt-2 text-2xl font-bold">Hypothèses classées</h2><p className="mt-1 text-sm text-muted">La confiance exprime la cohérence avec les éléments présents, pas une probabilité scientifique.</p><div className="mt-5 space-y-4">{analysis.hypotheses.map((item,i)=><article key={item.id} className="rounded-xl border border-line bg-panel p-4"><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="font-semibold">{i+1}. {item.label}</h3><span className="badge">{confidence(item.confidence)} · {Math.round(item.confidence*100)}%</span></div>{item.component&&<p className="mt-1 text-sm text-amber-200">Composant : {item.component}</p>}<div className="mt-4 grid gap-4 md:grid-cols-2"><div><strong className="text-sm text-emerald-200">Éléments favorables</strong><ul className="mt-2 list-inside list-disc text-sm text-muted">{item.supportingEvidence.length?item.supportingEvidence.map(x=><li key={x}>{x}</li>):<li>Aucun élément direct</li>}</ul></div><div><strong className="text-sm text-amber-200">À confirmer / contradictions</strong><ul className="mt-2 list-inside list-disc text-sm text-muted">{[...item.contradictingEvidence,...item.requiredConfirmation].map(x=><li key={x}>{x}</li>)}</ul></div></div></article>)}</div></section>
   {analysis.imageEvidence.length?<section className="card"><p className="eyebrow">Vision</p><h2 className="mt-2 text-2xl font-bold">Éléments visuels</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{analysis.imageEvidence.map(item=>{const image=detail.images.find(x=>x.id===item.imageId);return <article key={item.imageId} className="overflow-hidden rounded-xl border border-line bg-panel">{image&&<img src={`${origin}${image.url}`} alt={image.description||`Image technique ${image.category}`} width={480} height={320} loading="lazy" className="aspect-video w-full object-cover"/>}<div className="p-4"><p>{item.observation}</p><p className="mt-2 text-xs text-muted">{item.limitations.join(" · ")}</p></div></article>})}</div></section>:null}
   <section className="card border-amber-700" aria-labelledby="next-check-title"><p className="eyebrow">Action suivante</p><h2 id="next-check-title" className="mt-2 text-2xl font-bold">{current?.title||analysis.nextChecks[0]?.title||"Aucun contrôle proposé"}</h2>{current&&<><p className="mt-3 text-lg">{current.objective}</p><ol className="mt-5 space-y-3">{current.instructions.map((instruction,i)=><li key={instruction} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-primary font-bold">{i+1}</span><span>{instruction}</span></li>)}</ol>{current.safety_notes.length?<div className="mt-5 rounded-xl border border-warning/50 bg-amber-950/20 p-4"><strong className="text-amber-200">Sécurité</strong><ul className="mt-2 list-inside list-disc text-sm">{current.safety_notes.map(x=><li key={x}>{x}</li>)}</ul></div>:null}<div className="mt-6 border-t border-line pt-5">{current.expected_results.length?<><p className="label">Résultats attendus</p><div className="mb-4 grid gap-2 sm:grid-cols-2">{current.expected_results.map(item=><button key={item.result_id} type="button" className="min-h-12 cursor-pointer rounded-xl border border-line bg-panel p-3 text-left text-sm hover:border-amber-400" onClick={()=>setOutcome(`${item.label} — ${item.meaning}`)}><strong className="block">{item.label}</strong><span className="text-muted">{item.meaning}</span></button>)}</div></>:null}<label className="label" htmlFor="outcome">Résultat constaté *</label><textarea id="outcome" className="field min-h-24" value={outcome} onChange={e=>setOutcome(e.target.value)} placeholder="Décrivez la mesure ou l’observation obtenue"/><label className="label mt-4" htmlFor="comment">Commentaire technicien</label><textarea id="comment" className="field min-h-20" value={comment} onChange={e=>setComment(e.target.value)}/><button className="btn-primary mt-4" disabled={busy||!outcome.trim()} onClick={saveResult}>{busy?"Enregistrement…":"Enregistrer et réévaluer"}</button></div></>}</section>
  </main><aside className="space-y-6 lg:sticky lg:top-6">
   <section className="card"><h2 className="text-xl font-semibold">Informations manquantes</h2><div className="mt-4 space-y-4">{analysis.missingInformation.map(item=><article key={item.field} className="border-t border-line pt-4 first:border-0 first:pt-0"><div className="flex justify-between gap-3"><strong>{item.field}</strong><span className="badge">{item.priority}</span></div><p className="mt-1 text-sm text-muted">{item.reason}</p><p className="mt-2 text-sm text-amber-200">À obtenir : {item.howToObtain}</p></article>)}</div></section>
   <section className="card"><h2 className="text-xl font-semibold">Conclusion actuelle</h2><span className="badge mt-3">{analysis.finalConclusion.status.replaceAll("_"," ")}</span><p className="mt-3 text-muted">{analysis.finalConclusion.summary}</p></section>
   <section className="card"><h2 className="text-xl font-semibold">Avertissements</h2><ul className="mt-3 list-inside list-disc space-y-2 text-sm text-muted">{analysis.warnings.map(x=><li key={x}>{x}</li>)}</ul></section>
  </aside></div>
 </div>
}
